// <auto-generated />
using MarsRoverApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MarsRoverApi.Migrations
{
    [DbContext(typeof(MarsRoverDbContext))]
    partial class MarsRoverDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("MarsRoverApi.Models.Camera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoverId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoverId");

                    b.ToTable("Cameras");
                });

            modelBuilder.Entity("MarsRoverApi.Models.MarsPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CameraId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EarthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgSrc")
                        .HasColumnType("TEXT");

                    b.Property<int>("NasaPhotoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoverId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sol")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.HasIndex("RoverId");

                    b.ToTable("MarsPhotos");
                });

            modelBuilder.Entity("MarsRoverApi.Models.Rover", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LandingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LaunchDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rovers");
                });

            modelBuilder.Entity("MarsRoverApi.Models.Camera", b =>
                {
                    b.HasOne("MarsRoverApi.Models.Rover", null)
                        .WithMany("Cameras")
                        .HasForeignKey("RoverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarsRoverApi.Models.MarsPhoto", b =>
                {
                    b.HasOne("MarsRoverApi.Models.Camera", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarsRoverApi.Models.Rover", "Rover")
                        .WithMany()
                        .HasForeignKey("RoverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camera");

                    b.Navigation("Rover");
                });

            modelBuilder.Entity("MarsRoverApi.Models.Rover", b =>
                {
                    b.Navigation("Cameras");
                });
#pragma warning restore 612, 618
        }
    }
}
